### ISSUE TITLE
Getting what appears to be a false notice on some Reddit posts

### ISSUE THREAD

**Issue by jheiselman** [PlanetRenox/in0sight#3]
https://www.reddit.com/r/scifi/comments/8u2cxi/rumor_patrick_stewart_close_to_signing_deal_to/

This reddit post shows the zero-width characters notice for the title and in the comment at https://www.reddit.com/r/scifi/comments/8u2cxi/rumor_patrick_stewart_close_to_signing_deal_to/e1c08fg/

**Comment by PlanetRenox** [comment]
@jheiselman yes thank you for bringing this up, I am aware of this issue and will do something about it when I push out the next update. I've been busy with some other projects recently but I should come back and add some new changes in the upcoming months. I keep the extension on when I browse the internet so I notice a lot of these false positives that annoy me as well.

**Comment by PlanetRenox** [comment]
meanwhile, other developers are welcome to step in if they come across here, this whole issue is located inside:
https://github.com/PlanetRenox/in0sight/blob/master/cs/content.js
The fix can be simple if someone is willing to contribute. 
The extension reads the bodyContent and checks it against 'var Key', if the 0width is located inside a <p>, it inserts the notice, if it is not located inside a <p>, it shows a 10 sec notice on the top right of the screen. 

If someone spends the time to fix the false notice, they will be recognized as contributor/co-dev.

If not, i will get around to it as soon as i have the time to revisit the project.

**Comment by PlanetRenox-zz** [comment]
@jheiselman Update 1.1 has just been released and this issue should now be fixed.
